# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=255, blank=True, help_text='Nombre en espa\xf1ol. Si tiene traducci\xf3n al ingl\xe9s, ponla en el campo del nombre en ingl\xe9s. Sino, deja el campo del nombre en ingl\xe9s vac\xedo.', null=True, verbose_name='Sin\xf3nimo del producto', db_index=True)),
                ('nombre_en', models.CharField(max_length=255, blank=True, help_text='Nombre en espa\xf1ol. Si tiene traducci\xf3n al ingl\xe9s, ponla en el campo del nombre en ingl\xe9s. Sino, deja el campo del nombre en ingl\xe9s vac\xedo.', null=True, verbose_name='Sin\xf3nimo del producto', db_index=True)),
                ('nombre_es', models.CharField(max_length=255, blank=True, help_text='Nombre en espa\xf1ol. Si tiene traducci\xf3n al ingl\xe9s, ponla en el campo del nombre en ingl\xe9s. Sino, deja el campo del nombre en ingl\xe9s vac\xedo.', null=True, verbose_name='Sin\xf3nimo del producto', db_index=True)),
                ('slug', models.SlugField(help_text='Es parte de la URL. Debe ir en ingl\xe9s. Ejemplo: emergency-contraceptive-pills-3-days para http://e-lactancia/breastfeeding/emergency-contraceptive-pills-3-days. Un buen slug favorece aparecer en los primeros resultados de b\xfasquedas en Google.', unique=True, max_length=100, verbose_name='Slug')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n', db_index=True)),
            ],
            options={
                'verbose_name': 'Sin\xf3nimo de producto',
                'verbose_name_plural': 'Sin\xf3nimos de productos',
            },
        ),
        migrations.CreateModel(
            name='Aval',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('entidad', models.CharField(max_length=500, verbose_name='Organismo')),
                ('URL', models.URLField(default=b'', null=True, verbose_name='URL', blank=True)),
                ('logo', models.ImageField(default=b'img/apilam-grande.png', upload_to=b'images/avales', verbose_name='Logo')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible en la p\xe1gina Landing')),
                ('order', models.PositiveIntegerField()),
                ('extracto', models.CharField(help_text='Extracto del documento', max_length=1000, null=True, verbose_name='Extracto', blank=True)),
                ('extracto_en', models.CharField(help_text='Extracto del documento', max_length=1000, null=True, verbose_name='Extracto', blank=True)),
                ('extracto_es', models.CharField(help_text='Extracto del documento', max_length=1000, null=True, verbose_name='Extracto', blank=True)),
                ('carta', models.FileField(upload_to=b'papers', verbose_name='Documento PDF', blank=True)),
                ('carta_en', models.FileField(upload_to=b'papers', null=True, verbose_name='Documento PDF', blank=True)),
                ('carta_es', models.FileField(upload_to=b'papers', null=True, verbose_name='Documento PDF', blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n')),
            ],
            options={
                'ordering': ['entidad'],
                'verbose_name': 'Aval',
                'verbose_name_plural': 'Avales',
            },
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.CharField(max_length=1000, verbose_name='T\xedtulo')),
                ('autores', models.CharField(max_length=1000, null=True, verbose_name='Autores', blank=True)),
                ('publicacion', models.CharField(max_length=1000, null=True, verbose_name='Revista', blank=True)),
                ('anyo', models.PositiveSmallIntegerField(null=True, verbose_name='A\xf1o', blank=True)),
                ('abstract_link', models.URLField(help_text='Enlace al abstract del art\xedculo', max_length=500, null=True, blank=True)),
                ('full_text_link', models.URLField(help_text='Enlace al texto completo del art\xedculo', max_length=500, null=True, blank=True)),
                ('pdf', models.FileField(help_text='Sube el pdf del art\xedculo \xfanicamente si no est\xe1 disponible en ning\xfan enlace externo. De lo contrario, usa los campos de enlaces al abstract o al texto completo.', upload_to=b'papers', verbose_name='Documento PDF', blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n')),
            ],
            options={
                'verbose_name': 'Biblio',
                'verbose_name_plural': 'Biblio',
            },
        ),
        migrations.CreateModel(
            name='Cajita',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('titulo_en', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('titulo_es', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('texto_en', models.CharField(max_length=500, null=True, verbose_name='Texto')),
                ('texto_es', models.CharField(max_length=500, null=True, verbose_name='Texto')),
                ('link', models.URLField(help_text='Opcional. El link se abrir\xe1 en una nueva pesta\xf1a. Puede ser el enlace a un libro, web, post, noticia, etc.', null=True, verbose_name='Link', blank=True)),
                ('link_en', models.URLField(help_text='Opcional. El link se abrir\xe1 en una nueva pesta\xf1a. Puede ser el enlace a un libro, web, post, noticia, etc.', null=True, verbose_name='Link', blank=True)),
                ('link_es', models.URLField(help_text='Opcional. El link se abrir\xe1 en una nueva pesta\xf1a. Puede ser el enlace a un libro, web, post, noticia, etc.', null=True, verbose_name='Link', blank=True)),
                ('texto_link', models.CharField(help_text='Texto del link. Ejemplo: "Compar libro"; "Leer noticia"; "Ir a post"; etc', max_length=150, null=True, verbose_name='Texto del link', blank=True)),
                ('texto_link_en', models.CharField(help_text='Texto del link. Ejemplo: "Compar libro"; "Leer noticia"; "Ir a post"; etc', max_length=150, null=True, verbose_name='Texto del link', blank=True)),
                ('texto_link_es', models.CharField(help_text='Texto del link. Ejemplo: "Compar libro"; "Leer noticia"; "Ir a post"; etc', max_length=150, null=True, verbose_name='Texto del link', blank=True)),
                ('order', models.PositiveIntegerField()),
                ('visible', models.BooleanField(default=True, verbose_name='Visible en la p\xe1gina Landing')),
                ('publicidad', models.BooleanField(default=False, verbose_name='Es publicidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n')),
            ],
            options={
                'ordering': ['titulo'],
                'verbose_name': 'Cajita en Landing',
                'verbose_name_plural': 'Cajitas en landing',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comentario', models.CharField(max_length=500, verbose_name='Opini\xf3n')),
                ('leido', models.BooleanField(default=False, verbose_name='Opini\xf3n ya le\xedda')),
                ('lang', models.CharField(max_length=7, verbose_name='Idioma')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n')),
                ('alias', models.ForeignKey(related_name='comentario_alias', blank=True, to='lactancia.Alias', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type', models.CharField(default=b'c', help_text='Indica en qu\xe9 p\xe1gina aparecer\xe1 el texto.', max_length=1, verbose_name='Tipo de documento', choices=[(b'c', 'Cr\xe9ditos'), (b's', 'Patrocinadores'), (b'a', 'Avales'), (b'd', 'Donativos')])),
                ('order', models.PositiveSmallIntegerField(help_text='Indica, si aplica, el orden de la secci\xf3n/subsecci\xf3n de este documento. Ejemplo: "1";  "2"', null=True, verbose_name='Order', blank=True)),
                ('title', models.CharField(help_text='Ejemplo: Nuestra misi\xf3n.', unique=True, max_length=255, verbose_name='T\xedtulo')),
                ('title_en', models.CharField(help_text='Ejemplo: Nuestra misi\xf3n.', max_length=255, unique=True, null=True, verbose_name='T\xedtulo')),
                ('title_es', models.CharField(help_text='Ejemplo: Nuestra misi\xf3n.', max_length=255, unique=True, null=True, verbose_name='T\xedtulo')),
                ('content', models.CharField(max_length=15000, null=True, verbose_name='Contenido', blank=True)),
                ('content_en', models.CharField(max_length=15000, null=True, verbose_name='Contenido', blank=True)),
                ('content_es', models.CharField(max_length=15000, null=True, verbose_name='Contenido', blank=True)),
                ('visible', models.BooleanField(default=False, help_text='Marca esta casilla cuando el texto est\xe9 listo para que se muestre en la web. Mientras NO est\xe9 marcada, NO ser\xe1 visible en la web.', verbose_name='Visible en web')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n')),
            ],
            options={
                'ordering': ['type', 'order'],
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(unique=True, max_length=255, verbose_name='Nombre', db_index=True)),
                ('nombre_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Nombre', db_index=True)),
                ('nombre_es', models.CharField(max_length=255, unique=True, null=True, verbose_name='Nombre', db_index=True)),
                ('slug', models.SlugField(help_text='Es parte de la URL. Debe ir en ingl\xe9s. Ejemplo: emergency-contraceptive-pills-3-days para http://e-lactancia/breastfeeding/emergency-contraceptive-pills-3-days. Un buen slug favorece aparecer en los primeros resultados de b\xfasquedas en Google.', unique=True, max_length=100, verbose_name='Slug')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n', db_index=True)),
                ('relacionados', models.ManyToManyField(related_name='relacionados_rel_+', verbose_name='grupos con los que se relaciona', to='lactancia.Grupo', blank=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Icono',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fontawesome_nombre', models.CharField(help_text='Consulta los iconos en la web de <a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">FontAwesome</a>', max_length=100, null=True, verbose_name='Nombre del icono (en Fontawesome)', blank=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Icono',
                'verbose_name_plural': 'Iconos',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Idioma o escritura')),
                ('nombre_en', models.CharField(max_length=100, null=True, verbose_name='Idioma o escritura')),
                ('nombre_es', models.CharField(max_length=100, null=True, verbose_name='Idioma o escritura')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Idioma o escritura',
                'verbose_name_plural': 'Idiomas o escrituras',
            },
        ),
        migrations.CreateModel(
            name='LactUser',
            fields=[
                ('session', models.OneToOneField(primary_key=True, serialize=False, to='sessions.Session')),
                ('ip_address', models.CharField(max_length=256, verbose_name='Direcci\xf3n IP')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='e-Mail', blank=True)),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Nombre', blank=True)),
                ('perfil', models.CharField(max_length=2, verbose_name='Tipo de usuario (perfil)', choices=[(b'1', 'Pediatra'), (b'2', 'Ginec\xf3loga/o'), (b'14', 'M\xe9dico de familia'), (b'3', 'Otra especialidad m\xe9dica'), (b'4', 'Matrona'), (b'5', 'Enfermera/o'), (b'13', 'Farmac\xe9utico/a'), (b'6', 'Otro sanitario'), (b'7', 'Consultora lactancia (IBCLC, OMS)'), (b'8', 'Grupo de apoyo'), (b'9', 'Doula'), (b'10', 'Madre/Padre'), (b'11', 'Otro'), (b'12', 'An\xf3nimo')])),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Ciudad', blank=True)),
                ('longitude', models.DecimalField(null=True, verbose_name='Longitud', max_digits=9, decimal_places=6, blank=True)),
                ('latitude', models.DecimalField(null=True, verbose_name='Latitud', max_digits=9, decimal_places=6, blank=True)),
                ('country_name', models.CharField(max_length=255, null=True, verbose_name='Pa\xeds', blank=True)),
                ('country_code', models.CharField(max_length=30, null=True, verbose_name='C\xf3digo pa\xeds', blank=True)),
                ('country_code3', models.CharField(max_length=30, null=True, verbose_name='C\xf3digo pa\xeds 3', blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n', db_index=True)),
                ('user', models.ForeignKey(verbose_name='Nombre', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre comercial', db_index=True)),
                ('nombre_paises', models.CharField(max_length=700, null=True, verbose_name='Nombre comercial y pa\xeds', blank=True)),
                ('nombre_paises_en', models.CharField(max_length=700, null=True, verbose_name='Nombre comercial y pa\xeds', blank=True)),
                ('nombre_paises_es', models.CharField(max_length=700, null=True, verbose_name='Nombre comercial y pa\xeds', blank=True)),
                ('slug', models.SlugField(help_text='Es parte de la URL. Se crea autom\xe1ticamente a partir del nombre de la marca y el/los pa\xeds(es) donde se comercializa. El sistema se asegurar\xe1 de que sea \xfanico. Ejemplo:  Stadium (Mexico, Netherlands) -> stadium-mexico-netherlands para http://e-lactancia/breastfeeding/stadium-mexico-netherlands/tradename.', max_length=100, verbose_name='Slug')),
                ('comentario', models.CharField(max_length=255, null=True, verbose_name='Pa\xeds donde se comercializa', blank=True)),
                ('comentario_en', models.CharField(max_length=255, null=True, verbose_name='Pa\xeds donde se comercializa', blank=True)),
                ('comentario_es', models.CharField(max_length=255, null=True, verbose_name='Pa\xeds donde se comercializa', blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n', db_index=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(unique=True, max_length=255, verbose_name='Nombre')),
                ('nivel', models.CharField(default=b'info', max_length=7, verbose_name='Nivel del mensaje', choices=[(b'info', 'informaci\xf3n'), (b'success', '\xe9xito'), (b'warning', 'alerta'), (b'danger', 'peligro')])),
                ('tipo', models.CharField(max_length=15, verbose_name='Tipo de mensaje (nivel)', choices=[(b'cambio_riesgo', 'cambio en nivel del riesgo'), (b'farmacocinetica', 'mensaje en variable farmacocin\xe9tica'), (b'copyright', 'mensaje sobre copyrigh de marcas'), (b'diclaimer', 'mensaje sobre el uso de e-lactancia'), (b'comentario', 'comentario de usuarios')])),
                ('titulo', models.CharField(max_length=255, verbose_name='T\xedtulo mensaje', db_index=True)),
                ('titulo_en', models.CharField(max_length=255, null=True, verbose_name='T\xedtulo mensaje', db_index=True)),
                ('titulo_es', models.CharField(max_length=255, null=True, verbose_name='T\xedtulo mensaje', db_index=True)),
                ('contenido', models.CharField(db_index=True, max_length=5000, null=True, verbose_name='Cuerpo del mensaje', blank=True)),
                ('contenido_en', models.CharField(db_index=True, max_length=5000, null=True, verbose_name='Cuerpo del mensaje', blank=True)),
                ('contenido_es', models.CharField(db_index=True, max_length=5000, null=True, verbose_name='Cuerpo del mensaje', blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n', db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otras_escrituras',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Producto en otras escrituras', blank=True)),
                ('slug', models.SlugField(help_text='Es parte de la URL. Se crea autom\xe1ticamente a partir del nombre de la versi\xf3n "latinizada" del nombre. Ideal para aprender a produnciar chino, japon\xe9s, coreano o ruso. El sistema se asegurar\xe1 de que sea \xfanico. Ejemplo:  \u30a2\u30b7\u30af\u30ed\u30d3\u30eb -> ashikurobiru para http://e-lactancia/breastfeeding/ashikurobiru/writing.', max_length=100, verbose_name='Slug')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n', db_index=True)),
                ('escritura', models.ForeignKey(verbose_name='Idioma en que est\xe1 escrito el producto', blank=True, to='lactancia.Idioma', null=True)),
            ],
            options={
                'ordering': ['escritura__order', 'nombre'],
                'verbose_name': 'Otras escrituras del producto',
                'verbose_name_plural': 'Otras escrituras del producto',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_en', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('nombre_es', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Pa\xeds',
                'verbose_name_plural': 'Pa\xedses',
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('entidad', models.CharField(max_length=500, verbose_name='Organismo')),
                ('URL', models.URLField(default=b'', null=True, verbose_name='URL', blank=True)),
                ('logo', models.ImageField(default=b'img/apilam-grande.png', upload_to=b'images/avales', verbose_name='Logo')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible en la p\xe1gina Landing')),
                ('order', models.PositiveIntegerField()),
                ('descripcion', models.CharField(help_text='Breve texto describiendo el patrocinio', max_length=1000, null=True, verbose_name='Descripci\xf3n', blank=True)),
                ('descripcion_en', models.CharField(help_text='Breve texto describiendo el patrocinio', max_length=1000, null=True, verbose_name='Descripci\xf3n', blank=True)),
                ('descripcion_es', models.CharField(help_text='Breve texto describiendo el patrocinio', max_length=1000, null=True, verbose_name='Descripci\xf3n', blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n')),
                ('pais', models.ForeignKey(blank=True, to='lactancia.Pais', null=True)),
            ],
            options={
                'ordering': ['entidad'],
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(unique=True, max_length=255, verbose_name='Nombre', db_index=True)),
                ('nombre_en', models.CharField(max_length=255, unique=True, null=True, verbose_name='Nombre', db_index=True)),
                ('nombre_es', models.CharField(max_length=255, unique=True, null=True, verbose_name='Nombre', db_index=True)),
                ('slug', models.SlugField(help_text='Es parte de la URL. Debe ir en ingl\xe9s. Ejemplo: emergency-contraceptive-pills-3-days para http://e-lactancia/breastfeeding/emergency-contraceptive-pills-3-days. Un buen slug favorece aparecer en los primeros resultados de b\xfasquedas en Google.', unique=True, max_length=100, verbose_name='Slug')),
                ('comentario', models.CharField(max_length=10000, null=True, verbose_name='Comentario', blank=True)),
                ('comentario_en', models.CharField(max_length=10000, null=True, verbose_name='Comentario', blank=True)),
                ('comentario_es', models.CharField(max_length=10000, null=True, verbose_name='Comentario', blank=True)),
                ('no_alternativas', models.BooleanField(default=False, help_text='Marca esta casilla si no tiene sentido que el t\xe9rmino tenga altenativas. Por ejemplo, una enfermedad cong\xe9nita o adquirida.', verbose_name='No puede tener alternativas')),
                ('tiene_biblio', models.BooleanField(default=True, help_text='Indica si el producto poseera referencias bibliogr\xe1ficas. Si no las va a tener ni ahora ni en el futuro, debe desmarcarse esta casilla. Ejemplos de productos que pueden no tener bibliograf\xeda asociada son los de Fitoterapia', verbose_name='Tiene bibliografia (a\xf1adida o pendiente de a\xf1adir)')),
                ('csvfile', models.FileField(upload_to=b'papers/%Y/%m/', verbose_name='Importar biblio con fichero CSV', blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltima modificaci\xf3n', db_index=True)),
                ('biodisponibilidad', models.CharField(max_length=30, null=True, verbose_name='Biodisponibilidad', blank=True)),
                ('peso_molecular', models.CharField(max_length=30, null=True, verbose_name='Peso molecular', blank=True)),
                ('union_proteinas', models.CharField(max_length=30, null=True, verbose_name='Uni\xf3n a prote\xednas', blank=True)),
                ('volumen_distrib', models.CharField(max_length=30, null=True, verbose_name='Volumen de distribuci\xf3n', blank=True)),
                ('pka', models.CharField(max_length=30, null=True, verbose_name='pKa', blank=True)),
                ('t_maximo', models.CharField(max_length=30, null=True, verbose_name='Tiempo m\xe1ximo, Tmax', blank=True)),
                ('t_medio', models.CharField(max_length=30, null=True, verbose_name='Semivida de eliminaci\xf3n, Tiempo medio, T1/2', blank=True)),
                ('indice_leche_plasma', models.CharField(max_length=30, null=True, verbose_name='\xcdndice Leche/Plasma', blank=True)),
                ('dosis_teorica', models.CharField(max_length=30, null=True, verbose_name='Dosis te\xf3rica', blank=True)),
                ('dosis_relativa', models.CharField(max_length=30, null=True, verbose_name='Dosis relativa', blank=True)),
                ('dosis_terapeutica', models.CharField(max_length=30, null=True, verbose_name='Dosis relativa pedi\xe1trica', blank=True)),
                ('alternativas', models.ManyToManyField(to='lactancia.Producto', verbose_name='Lista de productos alternativos', blank=True)),
                ('biblio', models.ManyToManyField(to='lactancia.Bibliografia', verbose_name='bibliografia', blank=True)),
                ('grupo', models.ManyToManyField(to='lactancia.Grupo')),
                ('marcas', models.ManyToManyField(to='lactancia.Marca', verbose_name='Listado de marcas comerciales', blank=True)),
                ('referencia_grupos', models.ManyToManyField(help_text='Aparecer\xe1 un enlace a las fichas de estos grupos en la caja de comentario.', related_name='grupos_referenciados', verbose_name='Referencia a grupos de productos', to='lactancia.Grupo', blank=True)),
                ('referencia_otros_productos', models.ManyToManyField(help_text='Aparecer\xe1 un enlace a las fichas de estos productos en la caja de comentario.', related_name='referenciados', verbose_name='Referencia a otros productos', to='lactancia.Producto', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nivel', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('nombre_en', models.CharField(max_length=200, null=True, verbose_name='Nombre')),
                ('nombre_es', models.CharField(max_length=200, null=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripci\xf3n')),
                ('descripcion_en', models.CharField(max_length=500, null=True, verbose_name='Descripci\xf3n')),
                ('descripcion_es', models.CharField(max_length=500, null=True, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('lang', models.CharField(max_length=7, verbose_name='Idioma')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Acceso', db_index=True)),
                ('alias', models.ForeignKey(related_name='visita_alias', blank=True, to='lactancia.Alias', null=True)),
                ('grupo', models.ForeignKey(related_name='visita_grupo', blank=True, to='lactancia.Grupo', null=True)),
                ('marca', models.ForeignKey(related_name='visita_marca', blank=True, to='lactancia.Marca', null=True)),
                ('otra_escritura', models.ForeignKey(related_name='visita_otras_escrituras', blank=True, to='lactancia.Otras_escrituras', null=True)),
                ('prod', models.ForeignKey(related_name='visita_producto', blank=True, to='lactancia.Producto', null=True)),
                ('user', models.ForeignKey(to='lactancia.LactUser')),
            ],
        ),
        migrations.CreateModel(
            name='Visita_alias_perfil',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('perfil', models.CharField(max_length=2, verbose_name='Tipo de usuario (perfil)', choices=[(b'1', 'Pediatra'), (b'2', 'Ginec\xf3loga/o'), (b'14', 'M\xe9dico de familia'), (b'3', 'Otra especialidad m\xe9dica'), (b'4', 'Matrona'), (b'5', 'Enfermera/o'), (b'13', 'Farmac\xe9utico/a'), (b'6', 'Otro sanitario'), (b'7', 'Consultora lactancia (IBCLC, OMS)'), (b'8', 'Grupo de apoyo'), (b'9', 'Doula'), (b'10', 'Madre/Padre'), (b'11', 'Otro'), (b'12', 'An\xf3nimo')])),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('alias', models.ForeignKey(related_name='visita_alias_perfil', blank=True, to='lactancia.Alias', null=True)),
            ],
            options={
                'verbose_name': 'Visitas a sin\xf3nimos por perfil',
                'verbose_name_plural': 'Visitas a sin\xf3nimos por perfil',
            },
        ),
        migrations.CreateModel(
            name='Visita_alias_total',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('alias', models.ForeignKey(related_name='visita_alias_total', blank=True, to='lactancia.Alias', null=True)),
            ],
            options={
                'verbose_name': 'Visitas total a sin\xf3nimos',
                'verbose_name_plural': 'Visitas totales a sin\xf3nimos',
            },
        ),
        migrations.CreateModel(
            name='Visita_grupo_perfil',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('perfil', models.CharField(max_length=2, verbose_name='Tipo de usuario (perfil)', choices=[(b'1', 'Pediatra'), (b'2', 'Ginec\xf3loga/o'), (b'14', 'M\xe9dico de familia'), (b'3', 'Otra especialidad m\xe9dica'), (b'4', 'Matrona'), (b'5', 'Enfermera/o'), (b'13', 'Farmac\xe9utico/a'), (b'6', 'Otro sanitario'), (b'7', 'Consultora lactancia (IBCLC, OMS)'), (b'8', 'Grupo de apoyo'), (b'9', 'Doula'), (b'10', 'Madre/Padre'), (b'11', 'Otro'), (b'12', 'An\xf3nimo')])),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('grupo', models.ForeignKey(related_name='visita_grupo_perfil', blank=True, to='lactancia.Grupo', null=True)),
            ],
            options={
                'verbose_name': 'Visitas a grupo por perfil',
                'verbose_name_plural': 'Visitas a grupos por perfil',
            },
        ),
        migrations.CreateModel(
            name='Visita_grupo_total',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('grupo', models.ForeignKey(related_name='visita_grupo_total', blank=True, to='lactancia.Grupo', null=True)),
            ],
            options={
                'verbose_name': 'Visitas total a grupo',
                'verbose_name_plural': 'Visitas totales a grupos',
            },
        ),
        migrations.CreateModel(
            name='Visita_marca_perfil',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('perfil', models.CharField(max_length=2, verbose_name='Tipo de usuario (perfil)', choices=[(b'1', 'Pediatra'), (b'2', 'Ginec\xf3loga/o'), (b'14', 'M\xe9dico de familia'), (b'3', 'Otra especialidad m\xe9dica'), (b'4', 'Matrona'), (b'5', 'Enfermera/o'), (b'13', 'Farmac\xe9utico/a'), (b'6', 'Otro sanitario'), (b'7', 'Consultora lactancia (IBCLC, OMS)'), (b'8', 'Grupo de apoyo'), (b'9', 'Doula'), (b'10', 'Madre/Padre'), (b'11', 'Otro'), (b'12', 'An\xf3nimo')])),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('marca', models.ForeignKey(related_name='visita_marca_perfil', blank=True, to='lactancia.Marca', null=True)),
            ],
            options={
                'verbose_name': 'Visitas a marca por perfil',
                'verbose_name_plural': 'Visitas a marcas por perfil',
            },
        ),
        migrations.CreateModel(
            name='Visita_marca_total',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('marca', models.ForeignKey(related_name='visita_marca_total', blank=True, to='lactancia.Marca', null=True)),
            ],
            options={
                'verbose_name': 'Visitas total a marca',
                'verbose_name_plural': 'Visitas totales a marcas',
            },
        ),
        migrations.CreateModel(
            name='Visita_otras_escrituras_perfil',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('perfil', models.CharField(max_length=2, verbose_name='Tipo de usuario (perfil)', choices=[(b'1', 'Pediatra'), (b'2', 'Ginec\xf3loga/o'), (b'14', 'M\xe9dico de familia'), (b'3', 'Otra especialidad m\xe9dica'), (b'4', 'Matrona'), (b'5', 'Enfermera/o'), (b'13', 'Farmac\xe9utico/a'), (b'6', 'Otro sanitario'), (b'7', 'Consultora lactancia (IBCLC, OMS)'), (b'8', 'Grupo de apoyo'), (b'9', 'Doula'), (b'10', 'Madre/Padre'), (b'11', 'Otro'), (b'12', 'An\xf3nimo')])),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('otras_escrituras', models.ForeignKey(related_name='visita_otras_escrituras_perfil', blank=True, to='lactancia.Otras_escrituras', null=True)),
            ],
            options={
                'verbose_name': 'Visitas a otra escritura por perfil',
                'verbose_name_plural': 'Visitas a otras escrituras por perfil',
            },
        ),
        migrations.CreateModel(
            name='Visita_otras_escrituras_total',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('otras_escrituras', models.ForeignKey(related_name='visita_otras_escrituras_total', blank=True, to='lactancia.Otras_escrituras', null=True)),
            ],
            options={
                'verbose_name': 'Visitas total a otra escritura',
                'verbose_name_plural': 'Visitas totales a otras escrituras',
            },
        ),
        migrations.CreateModel(
            name='Visita_producto_perfil',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('perfil', models.CharField(max_length=2, verbose_name='Tipo de usuario (perfil)', choices=[(b'1', 'Pediatra'), (b'2', 'Ginec\xf3loga/o'), (b'14', 'M\xe9dico de familia'), (b'3', 'Otra especialidad m\xe9dica'), (b'4', 'Matrona'), (b'5', 'Enfermera/o'), (b'13', 'Farmac\xe9utico/a'), (b'6', 'Otro sanitario'), (b'7', 'Consultora lactancia (IBCLC, OMS)'), (b'8', 'Grupo de apoyo'), (b'9', 'Doula'), (b'10', 'Madre/Padre'), (b'11', 'Otro'), (b'12', 'An\xf3nimo')])),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('producto', models.ForeignKey(related_name='visita_producto_perfil', blank=True, to='lactancia.Producto', null=True)),
            ],
            options={
                'verbose_name': 'Visitas a producto por perfil',
                'verbose_name_plural': 'Visitas a productos por perfil',
            },
        ),
        migrations.CreateModel(
            name='Visita_producto_total',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visitas', models.IntegerField(default=0, verbose_name=b'Visitas', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='\xdaltimo c\xe1lculo')),
                ('producto', models.ForeignKey(related_name='visita_producto_total', blank=True, to='lactancia.Producto', null=True)),
            ],
            options={
                'verbose_name': 'Visitas total a producto',
                'verbose_name_plural': 'Visitas totales a productos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='riesgo',
            field=models.ForeignKey(verbose_name='Nivel de riesgo', to='lactancia.Riesgo'),
        ),
        migrations.AddField(
            model_name='otras_escrituras',
            name='producto_principal',
            field=models.ForeignKey(verbose_name='Nombre principal del producto', to='lactancia.Producto'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='producto',
            field=models.ForeignKey(verbose_name='Producto vinculado a este mensaje', blank=True, to='lactancia.Producto', null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='paises',
            field=models.ManyToManyField(to='lactancia.Pais', verbose_name='Paises donde se comercializa', blank=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='principios_activos',
            field=models.ManyToManyField(to='lactancia.Producto', verbose_name='Listado de principios activos', blank=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='grupo',
            field=models.ForeignKey(related_name='comentario_grupo', blank=True, to='lactancia.Grupo', null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='marca',
            field=models.ForeignKey(related_name='comentario_marca', blank=True, to='lactancia.Marca', null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='mensaje',
            field=models.ForeignKey(related_name='comentario_general', blank=True, to='lactancia.Mensaje', null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='otra_escritura',
            field=models.ForeignKey(related_name='comentario_otras_escrituras', blank=True, to='lactancia.Otras_escrituras', null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='prod',
            field=models.ForeignKey(related_name='comentario_producto', blank=True, to='lactancia.Producto', null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(blank=True, to='lactancia.LactUser', null=True),
        ),
        migrations.AddField(
            model_name='cajita',
            name='icono',
            field=models.ForeignKey(verbose_name='Icono', to='lactancia.Icono'),
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='productos',
            field=models.ManyToManyField(to='lactancia.Producto', verbose_name='Productos que referencian este trabajo', blank=True),
        ),
        migrations.AddField(
            model_name='aval',
            name='pais',
            field=models.ForeignKey(blank=True, to='lactancia.Pais', null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='producto_principal',
            field=models.ForeignKey(verbose_name='Nombre principal del producto', to='lactancia.Producto'),
        ),
    ]
